Loading /usr/share/emacs/site-lisp/debian-startup...
Loading 00debian...
Loading /usr/lib/xemacs-21.4.6/lisp/mule/auto-autoloads...
Loading /usr/share/xemacs21/packages/lisp/zenirc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/xemacs-devel/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/xemacs-base/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/w3/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/viper/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/view-process/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/vhdl/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/vc-cc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/vc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/tpu/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/tooltalk/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/tm/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/time/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/textools/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/text-modes/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/texinfo/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/supercite/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/strokes/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/speedbar/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/sounds-wav/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/sounds-au/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/slider/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/sieve/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/sh-script/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/sgml/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/semantic/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/scheme/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/rmail/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/reftex/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/psgml/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ps-print/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/prog-modes/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/pcomplete/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/pcl-cvs/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/pc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/os-utils/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/net-utils/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mmm-mode/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/misc-games/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mine/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mh-e/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mew/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mailcrypt/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/mail-lib/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/liece/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/jde/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ispell/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ilisp/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/igrep/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/idlwave/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ibuffer/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/hm--html-menus/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/gnus/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/gnats/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/games/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/fsf-compat/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/frame-icon/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/forms/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/footnote/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/eudc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/eterm/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/eshell/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/emerge/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/elib/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/eieio/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/efs/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/edt/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/edit-utils/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ediff/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/edebug/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/dired/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/debug/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/crisp/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/cookie/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/clearcase/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/cc-mode/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/calendar/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/calc/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/c-support/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/bbdb/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/auctex/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/apel/auto-autoloads.elc...
Loading /usr/share/xemacs21/packages/lisp/ada/auto-autoloads.elc...
Loading site-start...
Loading 00debian-vars...
Loading 20gnus-init...
Loading 50auctex...
Loading 50autoconf...
Loading 50debview...
Loading 50dpkg-dev-el...
Loading 50emacs-goodies-el...
Loading 50emacs-goodies-extra-el...
Loading 50maplev...
Loading 50maxima...
Loading 50preview-latex...
Loading 50x-symbol...
Loading x-symbol/auto-autoloads.el...
Loading x-symbol-xmas21...
Compiling /home/joe/elisp/maplev-working/maplev.el...
While compiling toplevel forms in file /home/joe/elisp/maplev-working/maplev.el:
  ** reference to free variable align-rules-list-type
While compiling maplev-mouse-yank-cut-buffer:
  ** assignment to free variable mouse-selection-click-count
While compiling maplev-mode:
  ** reference to free variable maplev-align-rules-list
  ** assignment to free variable align-mode-rules-list
  ** reference to free variable maplev-align-exclude-rules-list
  ** assignment to free variable align-mode-exclude-rules-list
While compiling maplev-cmaple-mode:
  ** assignment to free variable comint-use-prompt-regexp-instead-of-fields
While compiling the end of the data:
  ** The following functions are not known to be defined: 
    posn-point, event-start, x-get-cut-buffer, menu-bar-mode
Wrote /home/joe/elisp/maplev-working/maplev.elc
Done