#!/bin/bash

TST=$1

emacs --quick \
      --batch \
      --eval='(package-initialize)' \
      --eval='(setq ert-batch-backtrace-right-margin 200)' \
      --load=test-init.el \
      --load=ert \
      --load=maplev \
      --load=${TST}.el \
      --funcall=ert-run-tests-batch-and-exit |& tee ${TST}.log


